version: '4.0'

services:
  web1:
    image: mariorgzlpz-apache-image:p2
    volumes:
      - ./web_MarioRgzLpz:/var/www/localhost/htdocs
    container_name: web1
    networks:
      red_web:
        ipv4_address: 192.168.10.2
      red_servicios:
        ipv4_address: 192.168.20.2
    depends_on:
      - balanceador-traefik 

  web2:
    image: mariorgzlpz-apache-image:p2
    volumes:
      - ./web_MarioRgzLpz:/var/www/localhost/htdocs
    container_name: web2  
    networks:
      red_web:
        ipv4_address: 192.168.10.3
      red_servicios:
        ipv4_address: 192.168.20.3
    depends_on:
      - balanceador-traefik 

  web3:
    image: mariorgzlpz-apache-image:p2
    volumes:
      - ./web_MarioRgzLpz:/var/www/localhost/htdocs
    container_name: web3 
    labels:
      - "traefik.http.routers.web3.rule=Host(`localhost`)"
    networks:
      red_web:
        ipv4_address: 192.168.10.4
      red_servicios:
        ipv4_address: 192.168.20.4
    depends_on:
      - balanceador-traefik 

  web4:
    image: mariorgzlpz-apache-image:p2
    volumes:
      - ./web_MarioRgzLpz:/var/www/localhost/htdocs
    container_name: web4 
    labels:
      - "traefik.http.routers.web4.rule=Host(`localhost`)"
    networks:
      red_web:
        ipv4_address: 192.168.10.5
      red_servicios:
        ipv4_address: 192.168.20.5
    depends_on:
      - balanceador-traefik

  web5:
    image: mariorgzlpz-apache-image:p2
    volumes:
      - ./web_MarioRgzLpz:/var/www/localhost/htdocs
    container_name: web5   
    networks:
      red_web:
        ipv4_address: 192.168.10.6
      red_servicios:
        ipv4_address: 192.168.20.6
    depends_on:
      - balanceador-traefik

  web6:
    image: mariorgzlpz-apache-image:p2
    volumes:
      - ./web_MarioRgzLpz:/var/www/localhost/htdocs
    container_name: web6 
    networks:
      red_web:
        ipv4_address: 192.168.10.7
      red_servicios:
        ipv4_address: 192.168.20.7
    depends_on:
      - balanceador-traefik


  web7:
    image: mariorgzlpz-apache-image:p2
    volumes:
      - ./web_MarioRgzLpz:/var/www/localhost/htdocs
    container_name: web7
    networks:
      red_web:
        ipv4_address: 192.168.10.8
      red_servicios:
        ipv4_address: 192.168.20.8 
    depends_on:
      - balanceador-traefik 

  web8:
    image: mariorgzlpz-apache-image:p2
    volumes:
      - ./web_MarioRgzLpz:/var/www/localhost/htdocs
    container_name: web8
    networks:
      red_web:
        ipv4_address: 192.168.10.9
      red_servicios:
        ipv4_address: 192.168.20.9
    depends_on:
      - balanceador-traefik

  balanceador-traefik:
    image: mariorgzlpz-traefik-image:p2
    ports:
      - "80:80"
      - "8080:8080" # Para el dashboard de Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./dynamic.yml:/etc/traefik/conf.d/dynamic.yml"
      - "./traefik.yml:/etc/traefik/traefik.yml"
    container_name: balanceador-traefik
    networks:
      red_web:
        ipv4_address: 192.168.10.50

networks:
  red_web:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.1
  red_servicios:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.1